/// Human-readable Russian labels for catalog option values.
String settingOptionLabel(String raw) {
  const labels = <String, String>{
    '10': '10',
    '12': '12',
    '12h': '12 часов',
    '15': '15',
    '15m': '15 мин',
    '1d': '1 день',
    '1h': '1 час',
    '1m': '1 мин',
    '1y': '1 год',
    '2': '2',
    '20': '20',
    '24h': '24 часа',
    '3': '3',
    '30d': '30 дней',
    '30s': '30 сек',
    '4': '4',
    '5': '5',
    '5m': '5 мин',
    '6': '6',
    '7d': '7 дней',
    '8': '8',
    '90d': '90 дней',
    'DD.MM.YYYY': 'ДД.ММ.ГГГГ',
    'MM/DD/YYYY': 'ММ/ДД/ГГГГ',
    'YYYY-MM-DD': 'ГГГГ-ММ-ДД',
    'add_device': 'Добавить устройство',
    'all': 'Все',
    'any': 'Любые',
    'audio': 'Аудио',
    'auto': 'Авто',
    'balanced': 'Баланс',
    'blocked': 'Заблокированные',
    'bubbles': 'Пузыри',
    'button_only': 'Только кнопка',
    'calls': 'Звонки',
    'change_node': 'Сменить ноду',
    'community': 'Сообщество',
    'compact': 'Компактный',
    'compressed': 'Сжатое',
    'contact': 'Контакт',
    'contact_requests': 'Запросы в контакты',
    'contacts': 'Контакты',
    'corporate_verified': 'Корпоративная проверка',
    'ctrl_enter': 'Ctrl+Enter',
    'daily': 'Ежедневно',
    'dark': 'Тёмная',
    'delete_profile': 'Удалить профиль',
    'delivery_errors': 'Ошибки доставки',
    'device_encrypted': 'Шифрование на устройстве',
    'device_only': 'Только устройство',
    'device_secure_store': 'Защищённое хранилище устройства',
    'direct': 'Напрямую',
    'documents': 'Документы',
    'drafts': 'Черновики',
    'email': 'Email',
    'empty_profile': 'Пустой профиль',
    'en': 'English',
    'enter': 'Enter — отправить',
    'everyone': 'Всем',
    'export': 'Экспорт',
    'extra_large': 'Очень крупный',
    'favorites': 'Избранное',
    'flat': 'Плоские',
    'folders': 'Папки',
    'from_now': 'С текущего момента',
    'from_pairing': 'С момента привязки',
    'full': 'Полный текст',
    'generic': 'Обычный',
    'gesture': 'Жест',
    'groups': 'Группы',
    'hardware_keystore': 'Аппаратный keystore',
    'hidden': 'Скрыто',
    'hidden_chats': 'Скрытые чаты',
    'high': 'Высокое',
    'http': 'HTTP',
    'immediate': 'Сразу',
    'immediately': 'Сразу',
    'invites': 'Приглашения',
    'keys': 'Ключи',
    'large': 'Крупный',
    'light': 'Светлая',
    'local_file': 'Локальный файл',
    'local_only': 'Только локально',
    'low': 'Низкое',
    'manual': 'Вручную',
    'media': 'Медиа',
    'mentions': 'Упоминания',
    'messages': 'Сообщения',
    'monthly': 'Ежемесячно',
    'never': 'Никогда',
    'nobody': 'Никто',
    'node_errors': 'Ошибки ноды',
    'none': 'Нет',
    'normal': 'Обычный',
    'off': 'Выкл',
    'original': 'Оригинал',
    'permanent': 'Постоянно',
    'personal': 'Личное',
    'personal_node': 'Личная нода',
    'personal_node_s3': 'Личная нода + S3',
    'photos': 'Фото',
    'pin': 'PIN',
    'profile': 'Профиль',
    'push': 'Push',
    'qr': 'QR',
    'qr_verified': 'QR подтверждён',
    'recipient_cache': 'Кэш получателя',
    'recovery_key': 'Ключ восстановления',
    'replicated_nodes': 'Реплицированные ноды',
    'replies': 'Ответы',
    'ru': 'Русский',
    'safe_profile': 'Безопасный профиль',
    'secret_command': 'Секретная команда',
    'security': 'Безопасность',
    'selected': 'Выбранные',
    'selected_chats': 'Выбранные чаты',
    'selected_node': 'Выбранная нода',
    'selected_s3': 'Выбранный S3',
    'sender_device': 'Устройство отправителя',
    'sender_only': 'Только отправитель',
    'settings': 'Настройки',
    'single_use': 'Одноразовый',
    'small': 'Маленький',
    'socks5': 'SOCKS5',
    'system': 'Как в системе',
    'temporary': 'Временно',
    'through_node': 'Через ноду',
    'trusted': 'Доверенные',
    'trusted_device': 'Доверенное устройство',
    'unknown': 'Неизвестные',
    'unverified': 'Непроверенные',
    'videos': 'Видео',
    'view_keys': 'Смотреть ключи',
    'weekly': 'Еженедельно',
    'wifi_only': 'Только Wi‑Fi',
  };
  return labels[raw] ?? raw;
}
