#!/usr/bin/env bash
# Dev mTLS PKI for Gateway + node/client identities (ADR-0010).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="${ROOT}/config/mtls"
CLIENTS="${DIR}/clients"
FP_SCRIPT="${ROOT}/scripts/cert-fingerprint.sh"
DAYS=825

mkdir -p "$CLIENTS"

if [[ -f "${DIR}/ca.crt" && "${FORCE:-0}" != "1" ]]; then
  echo "Certs already exist at ${DIR} (set FORCE=1 to regenerate)"
  exit 0
fi

echo "Generating dev CA and certificates in ${DIR}..."

openssl genrsa -out "${DIR}/ca.key" 4096 2>/dev/null
openssl req -x509 -new -nodes -key "${DIR}/ca.key" -sha256 -days 3650 \
  -subj "/CN=Messenger Dev CA" -out "${DIR}/ca.crt"

openssl genrsa -out "${DIR}/gateway.key" 2048 2>/dev/null
openssl req -new -key "${DIR}/gateway.key" -subj "/CN=localhost" -out "${DIR}/gateway.csr"
openssl x509 -req -in "${DIR}/gateway.csr" -CA "${DIR}/ca.crt" -CAkey "${DIR}/ca.key" \
  -CAcreateserial -out "${DIR}/gateway.crt" -days "$DAYS" -sha256

make_client() {
  local name="$1"
  openssl genrsa -out "${CLIENTS}/${name}.key" 2048 2>/dev/null
  openssl req -new -key "${CLIENTS}/${name}.key" -subj "/CN=${name}" -out "${CLIENTS}/${name}.csr"
  openssl x509 -req -in "${CLIENTS}/${name}.csr" -CA "${DIR}/ca.crt" -CAkey "${DIR}/ca.key" \
    -CAcreateserial -out "${CLIENTS}/${name}.crt" -days "$DAYS" -sha256
}

NODE_IDS=(gateway-local home-local relay-local storage-local media-local turn-local client-dev)
for id in "${NODE_IDS[@]}"; do
  make_client "$id"
done

FP_FILE="${DIR}/fingerprints.env"
FPS=()
for id in "${NODE_IDS[@]}"; do
  FPS+=("$("bash" "$FP_SCRIPT" "${CLIENTS}/${id}.crt")")
done

ALLOWED_LIST=$(IFS=,; echo "${FPS[*]}")

cat > "$FP_FILE" <<EOF
# Auto-generated by scripts/generate-mtls-certs.sh — source into .env for mTLS dev
GATEWAY_TLS_ENABLED=false
GATEWAY_TLS_PORT=8447
GATEWAY_TLS_CERT_PATH=/mtls/gateway.crt
GATEWAY_TLS_KEY_PATH=/mtls/gateway.key
GATEWAY_TLS_CLIENT_CA_PATH=/mtls/ca.crt
GATEWAY_MTLS_MODE=optional
ALLOWED_GATEWAY_CLIENT_FINGERPRINTS=${ALLOWED_LIST}
ALLOWED_TLS_CERT_FINGERPRINTS=${ALLOWED_LIST}
MTLS_MODE=report
# Per-node fingerprints (set NODE_TLS_CERT_FINGERPRINT on each service):
# gateway-local=$("bash" "$FP_SCRIPT" "${CLIENTS}/gateway-local.crt")
# home-local=$("bash" "$FP_SCRIPT" "${CLIENTS}/home-local.crt")
# relay-local=$("bash" "$FP_SCRIPT" "${CLIENTS}/relay-local.crt")
# storage-local=$("bash" "$FP_SCRIPT" "${CLIENTS}/storage-local.crt")
# media-local=$("bash" "$FP_SCRIPT" "${CLIENTS}/media-local.crt")
# turn-local=$("bash" "$FP_SCRIPT" "${CLIENTS}/turn-local.crt")
# client-dev=$("bash" "$FP_SCRIPT" "${CLIENTS}/client-dev.crt")
EOF

chmod 600 "${DIR}/ca.key" "${DIR}/gateway.key" "${CLIENTS}"/*.key 2>/dev/null || true
echo "Done. See ${FP_FILE}"
echo "Client dev: ${CLIENTS}/client-dev.crt + client-dev.key"
echo "Enable: GATEWAY_TLS_ENABLED=true GATEWAY_MTLS_MODE=required"
