import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:messenger_app/core/theme/app_theme.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'scenes.dart';
import 'states_manifest.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('capture all UI screenshots', (tester) async {
    SharedPreferences.setMockInitialValues({});
    tester.view.physicalSize = const Size(780, 1688);
    tester.view.devicePixelRatio = 2;
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);

    final out = Directory('${Directory.current.path}/docs/ui-screenshots');
    if (out.existsSync()) out.deleteSync(recursive: true);
    out.createSync(recursive: true);

    final captured = <ScreenshotState>[];
    final skipped = <ScreenshotState>[];
    final failed = <String>[];

    for (final state in kScreenshotStates) {
      if (state.skipped) {
        skipped.add(state);
        continue;
      }
      try {
        print('CAPTURING ${state.fileStem}');
        final key = GlobalKey();
        await tester.pumpWidget(
          MaterialApp(
            theme: AppTheme.dark(),
            home: RepaintBoundary(key: key, child: buildScreenshotScene(state)),
          ),
        );
        await tester.pump();
        final boundary = tester.renderObject<RenderRepaintBoundary>(find.byKey(key));
        final image = await tester.runAsync(() => boundary.toImage(pixelRatio: 1.0));
        if (image == null) throw StateError('toImage returned null');
        final byteData = await tester.runAsync(() => image.toByteData(format: ui.ImageByteFormat.png));
        image.dispose();
        if (byteData == null) throw StateError('toByteData returned null');
        File('${out.path}/${state.fileStem}.png').writeAsBytesSync(byteData.buffer.asUint8List());
        captured.add(state);
        print('OK ${state.fileStem}');
        await tester.pumpWidget(const SizedBox.shrink());
        await tester.pump();
      } catch (e, st) {
        failed.add('${state.fileStem}: $e');
        print('FAILED ${state.fileStem}: $e\n$st');
        await tester.pumpWidget(const SizedBox.shrink());
        await tester.pump();
      }
    }

    final index = StringBuffer()
      ..writeln('# UI screenshots catalog')
      ..writeln()
      ..writeln('Generated by `flutter test test/ui_screenshots/capture_test.dart`.')
      ..writeln()
      ..writeln('| Group | State | Title | File |')
      ..writeln('| --- | --- | --- | --- |');
    for (final s in captured) {
      index.writeln('| `${s.group}` | `${s.id}` | ${s.titleRu} | `${s.fileStem}.png` |');
    }
    if (skipped.isNotEmpty) {
      index
        ..writeln()
        ..writeln('## Skipped')
        ..writeln()
        ..writeln('| Group | State | Reason |')
        ..writeln('| --- | --- | --- |');
      for (final s in skipped) {
        index.writeln('| `${s.group}` | `${s.id}` | ${s.skipReason ?? "—"} |');
      }
    }
    if (failed.isNotEmpty) {
      index
        ..writeln()
        ..writeln('## Failed')
        ..writeln()
        ..writeln('| Detail |')
        ..writeln('| --- |');
      for (final f in failed) {
        index.writeln('| `$f` |');
      }
    }
    index
      ..writeln()
      ..writeln(
        '**Captured:** ${captured.length} · **Skipped:** ${skipped.length} · '
        '**Failed:** ${failed.length} · **Total in manifest:** ${kScreenshotStates.length}',
      );
    File('${out.path}/INDEX.md').writeAsStringSync(index.toString());

    expect(failed, isEmpty, reason: failed.join('\n'));
    expect(captured.length, greaterThan(60));
  }, timeout: const Timeout(Duration(minutes: 5)));
}
