server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Flutter web — всё через index.html (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэш для статики
    location ~* \.(js|css|png|jpg|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    # Без кэша для index.html
    location = /index.html {
        add_header Cache-Control "no-cache";
    }
}
